# ============================================================
# pin_assignments.xdc — Board-level I/O constraints
# Target: ZYNQ XC7Z020-CLG484
# NOTE: Port names use "_0" suffix as generated by BD wrapper
# ============================================================

set_property IOSTANDARD LVCMOS33 [get_ports *]

# Global clock and reset
set_property PACKAGE_PIN U18 [get_ports sys_clk_0]
set_property PACKAGE_PIN N16 [get_ports sys_rst_n_0]

# J3 expansion
set_property PACKAGE_PIN K14 [get_ports uart2_rx_0]
set_property PACKAGE_PIN M15 [get_ports uart2_tx_0]

# J4 expansion — clock and reference
set_property PACKAGE_PIN V5  [get_ports ref_clk_10m_0]
set_property PACKAGE_PIN T11 [get_ports pps_clk_0]

# J4 expansion — microwave
set_property PACKAGE_PIN U5 [get_ports mw_i_0]
set_property PACKAGE_PIN T5 [get_ports mw_q_0]

# J4 expansion — AD9280
set_property PACKAGE_PIN T9  [get_ports {ad_data_0[0]}]
set_property PACKAGE_PIN U10 [get_ports {ad_data_0[1]}]
set_property PACKAGE_PIN U8  [get_ports {ad_data_0[2]}]
set_property PACKAGE_PIN U9  [get_ports {ad_data_0[3]}]
set_property PACKAGE_PIN V8  [get_ports {ad_data_0[4]}]
set_property PACKAGE_PIN W8  [get_ports {ad_data_0[5]}]
set_property PACKAGE_PIN U7  [get_ports {ad_data_0[6]}]
set_property PACKAGE_PIN V7  [get_ports {ad_data_0[7]}]
set_property PACKAGE_PIN W6  [get_ports ad_otr_0]
set_property PACKAGE_PIN W14 [get_ports adc_clk_0]

# J4 expansion — pulse outputs
set_property PACKAGE_PIN V6 [get_ports pulse_0_0]
set_property PACKAGE_PIN Y7 [get_ports pulse_1_0]
set_property PACKAGE_PIN Y6 [get_ports pulse_2_0]
set_property PACKAGE_PIN Y9 [get_ports pulse_3_0]
